### ISSUE TITLE
Web API endpoints

### ISSUE THREAD

**Issue by desmondhume** [jsncmgs1/spotify_ex#1]
Hi @jsncmgs1!
Thank you for your work!
I'm opening this issue to know if you're interested in extending this package to Web API endpoints (other than the authentication flow). I'm going to work a lot with spotify + elixir in the next months, and I'd like to contribute to this package more than creating a new one with another name (packages pollution is a problem nowadays :D ). 
Let me know if you'd accept pull requests about api endpoints mapping and spotify entity abstractions (structs and stuff like that).

Thanks!

**Comment by jsncmgs1** [comment]
Hey, glad this is/was useful for someone!  I would definitely take contributions, no need to keep it limited to OAuth.  The only thing I'd be concerned about would be making sure we specify which parts of the API we cover in the README.

**Comment by desmondhume** [comment]
I think we could do something like this https://github.com/edgurgel/tentacat (list of covered endpoints with nested resources), and keeping an updated Roadmap as well. 
Also a checklist with checked/unchecked points would do the job well.
Let me know!

**Comment by jsncmgs1** [comment]
I think a checklist is easier to grok.  Once there is more than just OAuth I can extract the OAuth example and link to it instead of polluting the README.
