### ISSUE TITLE
Add tracks to playlist via body

### ISSUE THREAD

**Issue by steveklebanoff** [jsncmgs1/spotify_ex#14]
In explaining the `uris` parameter of the Create Playlist API, The [Spotify API docs](https://developer.spotify.com/web-api/add-tracks-to-playlist/#tablepress-102) state:

> Note: it is likely that passing a large number of track URIs as a query parameter will exceed the maximum length of the request URI. When adding a large number of tracks it is recommended to pass them in the request body, see below.

It looks like the current implementation of add_tracks in spotify_ex's [playlist.ex](https://github.com/jsncmgs1/spotify_ex/blob/c802f4a9b0b45c10940fcde6b6d07bc155942f5f/lib/spotify/playlist.ex#L277) uses query parameters, but states:

```
You can also pass the URI param in the request body. Use `add_tracks/2`. See Spotify docs.
      Spotify.Playlist.add_tracks("123", "456", uris: "spotify:track:4iV5W9uYEdYUVa79Axb7Rh")
      # => {:ok, %{"snapshot_id" => "foo"}}
```

I may be missing something, but I don't see `add_tracks/2` defined, and looking through the code I don't see a way to add tracks via the request body.  Am I missing something obvious, or is adding support for adding tracks via the request body something that should be added?

Additionally: is there any reason to support adding tracks through a query parameter, or would it be better to just always add them through the request body?

**Comment by jsncmgs1** [comment]
it's something that should've been in there that I probably sped through and forgot. I wouldn't be surprised if there were more endpoints with this issue.  If you'd like to open a PR I'd gladly merge, or I can fix it tomorrow at lunch.

**Comment by steveklebanoff** [comment]
OK, cool.  Would love to see this fixed.  If you have time today that would be awesome.  I'm not sure when I'd have a chance to work on a PR for this myself

**Comment by jsncmgs1** [comment]
Busier than I thought, I _should_ have time to look at it Friday afternoon.

**Comment by jsncmgs1** [comment]
I've added body support to the playlist api in the new 2.0.2 release.  Life has been crazy lately so I didn't check the rest of the library but I wanted to get this out there.

**Comment by steveklebanoff** [comment]
awesome, many thanks @jsncmgs1 !!
