### ISSUE TITLE
Authentication does not fail transparently when client secret is wrong

### ISSUE THREAD

**Issue by jdpopkin** [jsncmgs1/spotify_ex#15]
When the client secret is configured incorrectly, attempting to authenticate should yield an error. Instead, `Spotify.Authentication.authenticate` still returns `{:ok, conn}`, but Spotify-related token cookies will be nil.

There's already some kind of check for this, in that `AuthenticationClient` checks if the `HTTPoison.post` succeeded or not. But it looks like `HTTPoison.post` reports success even when the response code is 400.

You can see this yourself if you configure a client secret incorrectly and add a couple `IO.inspect` calls:

```
def post(params) do
  case AuthRequest.post(params) do
    {:ok, %HTTPoison.Response{status_code: code, body: body}} ->
      with {:ok, response} <- Poison.decode(body) do
        IO.inspect(code) # todo remove
        IO.inspect(response) # todo remove
        {:ok, Spotify.Credentials.get_tokens_from_response(response)}
      else
        _unmatched ->
          raise(AuthenticationError, "Error parsing response from Spotify")
      end
    {:error, %HTTPoison.Error{reason: reason}} ->
      { :error, reason }
  end
end
```

With an invalid client secret, I see

```
400
%{"error" => "invalid_client", "error_description" => "Invalid client secret"}
```

in my logs.

**Comment by jsncmgs1** [comment]
Thanks for reporting this. I'll take a look as soon as time allows.
