### ISSUE TITLE
(question) Can this be used for Client Credentials Flow?

### ISSUE THREAD

**Issue by deini** [jsncmgs1/spotify_ex#19]
In the README and the code I see this being used with Authorization Code. I can't seem to find how to get it working with Client Credentials Flow, just wondering if this is implemented and I'm just missing it or it currently only supports Authorization Code flow?

**Comment by jsncmgs1** [comment]
Currently not, the initial request for the token must have a `grant_type` parameter of `client_credentials` : https://developer.spotify.com/web-api/authorization-guide/#client-credentials-flow

Right now the auth type is hardcoded to use authorization flow: https://github.com/jsncmgs1/spotify_ex/blob/master/lib/spotify/authentication.ex#L106

Another config setting could be introduced to allow specifying which flow you'd like to use, or you could make the initial token request manually and use the library from there.

**Comment by deini** [comment]
👍 I think I'll go with requesting the token manually for now. Thanks for the info
