### ISSUE TITLE
Add support for Player API after beta phase 

### ISSUE THREAD

**Issue by jsncmgs1** [jsncmgs1/spotify_ex#21]

**Comment by jsncmgs1** [comment]
If you'd like to contribute for hacktoberfest, these end points are in beta but id gladly merge if someone wanted to add the beta endpoints.
https://developer.spotify.com/documentation/web-api/reference/player/

**Comment by adamzaninovich** [comment]
I'm definitely interested in adding this. I want to use the Spotify Connect API in an upcoming Nerves project. I'll try to tackle it if I get some time in the coming days.

**Comment by jsncmgs1** [comment]
@adamzaninovich would be awesome if you were able to tackle this, thanks again.
