### ISSUE TITLE
Expired token error comes with :ok atom

### ISSUE THREAD

**Issue by zacstewart** [jsncmgs1/spotify_ex#25]
I'm trying to wrap `Spotify` with a little module that automatically refreshes expired tokens like so

```elixir
defmodule SpotifyAgent do
  def call(conn, func) do
    result = func.(conn)
    case result do
      {:ok, response} ->
        result
      {:error,  e} ->
        refresh(conn)
        call(conn, func)
    end
  end

  defp refresh(conn) do
    Spotify.refresh(conn)
  end
end
```

However, 401 Expired responses are coming through as `:ok`. Is this expected? I'd think it'd be an `:error`.

```elixir
{:ok, %{"error" => %{"message" => "The access token expired", "status" => 401}}}
```

**Comment by jsncmgs1** [comment]
Yeah, that seems more logical. PRs welcome, otherwise I can get to it next week hopefully.

**Comment by zacstewart** [comment]
Thanks for the response. I may try taking a stab at a PR but maybe not. I'm very new to Elixir working on a beginner project using your package.

**Comment by jsncmgs1** [comment]
@zacstewart What's happening is HTTPoision is recognizing it as a valid HTTP response, so it's giving it an `:ok`, the actual error is from spotify. If you pattern match on the inner map, you should be fine.

https://github.com/jsncmgs1/spotify_ex/blob/91241147b7bbc103b9e135e44500f52c367039ac/lib/spotify/authentication_client.ex

**Comment by zacstewart** [comment]
That makes sense, and that's what I did to get around it. It just seemed strange for an API because I was expecting the atom to represent an API-level success or failure, not HTTP-level.

**Comment by bryannaegele** [comment]
I haven't had time yet to refine this, but if the approach I took to this issue is appealing, I'd be happy to wrap it up and open a PR. I was going to move the max_age on the refresh token to be configurable and submit a PR but I've been rather busy. 

The basic idea is to simply expire the auth token which will automatically kick the established flow into obtaining a new token using the refresh token. It's worked rather well for my use.

https://github.com/jsncmgs1/spotify_ex/compare/master...bryannaegele:master

**Comment by jsncmgs1** [comment]
@bryannaegele I'm at an airport with bad connection so I'm not diving as deep into the docs as I should (I've also had a beer or 2) but IIRC doesn't the access token have a lifetime of 1 hour? Shouldn't the Spotify expiration kick in before yours ever does? Forgive me if I'm misunderstanding.

**Comment by bryannaegele** [comment]
I'm setting the access token's cookie expiry to what is returned by Spotify (though I should subtract a minute off for latency). The refresh token's cookie is set for 30 days (arbitrary). When you initially obtain an auth & refresh token, it has a timestamp on the response `expires_in` that tells you when the auth token will expire. I'm just transferring that to the cookie so it will expire.

If the access token's cookie expires, it isn't sent with the client's request to somebody's app. Your existing auth code already looks for the refresh token's cookie in this situation and attempts to obtain a new auth token.

In the situation where neither cookie is present (if they both expired or it's their first login), your normal auth flow kicks in, requiring the user to sign in again to Spotify.

**Comment by lucasmedeirosleite** [comment]
I can help you guys if you want! :)

**Comment by jsncmgs1** [comment]
Completely forgot about this :( I have no problem merging a good solution.
