### ISSUE TITLE
Add support for Library API

### ISSUE THREAD

**Issue by katbow** [jsncmgs1/spotify_ex#29]
I don't think any of the endpoints found in the [library API](https://developer.spotify.com/web-api/library-endpoints/) are found in other modules (i.e. not duplicated).

Would be great to have a module for this section. I'd be happy to implement & contribute this feature.

**Comment by jsncmgs1** [comment]
Hi @katbow, some of them are in there (`/me/albums`) for example, but there are certainly some missing, I'm happy to merge a Library module as long as it's tested and follows the pattern the other modules follow. Thanks for the help!

**Comment by adamzaninovich** [comment]
Was going to work on this, but it looks like there was a PR merged already. Is there still more to do on this issue?

**Comment by katbow** [comment]
Hey! I meant to close this. I've added all the Library functionality that wasn't already part of other APIs.
