### ISSUE TITLE
Refactor test directory & naming conventions

### ISSUE THREAD

**Issue by katbow** [jsncmgs1/spotify_ex#34]
Test directory structure & naming conventions are not idiomatic Elixir, which makes it more difficult to find things if trying to follow the norm. 

**Actual test structure**

* Tests for files in `lib/spotify/` are directly in `test/` (no subfolder)
* Test modules are namespaced as `Album` (in the case of testing `Spotify.Album`)

**Expected test structure**

* Tests for files in `lib/spotify/` to be in the directory `test/spotify/`
* Test modules to be namespaced as `Spotify.AlbumTest` (in the case of testing `Spotify.Album`)

Thoughts on this @jsncmgs1 ?

**Comment by jsncmgs1** [comment]
I have no preference but will gladly merge a PR if you're willing to take this on. Thanks!

**Comment by adamzaninovich** [comment]
@katbow @jsncmgs1 Hey y'all, I had a few hours to kill tonight and decided to tackle this issue. Let me know if this looks good, or if I should do anything differently. Thanks!

**Comment by katbow** [comment]
I haven't done anything on this yet, so it's all yours!
