### ISSUE TITLE
Spotify.Cookies.set_cookies indirectly halts redirects

### ISSUE THREAD

**Issue by dnlsandiego** [jsncmgs1/spotify_ex#36]
It looks like `Spotify.Cookies.set_cookies` indirectly halts redirects because it explicitly sets the `conn`'s HTTP response status to 200. Which causes redirects to just be stuck in a page with a "You are being redirected" message instead of actually prompting the browser to redirect to a specific page. 

Any reason why `Spotify.Cookies.set_cookies` explicitly sets the status to 200? Is it safe to remove or move somewhere else? If so, I'd be glad to put a PR together for it.

(Another argument for removing the setting of the HTTP status in the there is that in a function named `set_cookies` it's quite out of scope of its responsibilities to set the http status along with setting the cookies)

**Comment by jsncmgs1** [comment]
I agree with all of this. Happy to merge a PR.
