### ISSUE TITLE
Can't use without cookies?

### ISSUE THREAD

**Issue by adamzaninovich** [jsncmgs1/spotify_ex#4]
It looks like any function that makes a request to Spotify needs a Plug.Conn with a cookie inside that contains the auth tokens. This effectively limits this library to be used only in conjunction with a web application.

What about providing some way to store the auth data in a process instead so that one could use this library without a browser involved?

**Comment by jsncmgs1** [comment]
My use case never involved not having the browser so I definitely didn't think of that, but I would be open to it.

**Comment by adamzaninovich** [comment]
I'd definitely like to help, though I'm not really sure what direction to take with it. Is it only using the Conn to store and retrieve the auth tokens?

**Comment by adamzaninovich** [comment]
BTW, so you know where I'm coming from, my use case is a bot that compiles Spotify track URIs posted in a Slack channel into a playlist.

**Comment by jsncmgs1** [comment]
Yes, the conn just is for handling auth tokens.  I would have to put some thought into the best way to do this, and honestly it's not something I would be able to do given other work at the moment.  I'd be happy to talk it out and would certainly merge a good solution.  Off the top of my head (I'm at work ATM) I'd think the first step might be to extract the `some_api_call_url` functions into their own modules so we could include them in seperate modules for building up requests that don't need a conn.  But like I said, thats just off the top of my head :)

**Comment by adamzaninovich** [comment]
That's cool, I'm definitely fine with doing an implementation if we can come up with a good design.

It looks like it boils down to how the auth headers are created in `Client`. The "conn" that gets passed all the way through is really just a handle to some auth container (whether it's using a `Plug.Conn` to get tokens from a session or maybe a pid to get tokens from an agent doesn't matter until you get to the `Client`).

What about breaking the header stuff in `Client` out into something like `Client.SessionAuth` and `Client.ProcessAuth` modules and making that a configuration option. Then the `{get,put,post,delete}_headers` could be implemented in those modules and used in `Client`.

IDK, I like this because it just moves the user interaction into config and then they use the library the same way as always, but maybe that's terrible.

Another option would be like you're suggesting (if I understand correctly) where we break up each endpoint module into 3 parts `Album`, `Album.URLs`, `Album.<not sure what to call this>`. Where `Album` keeps the original API where you pass in a conn and the new `Album.<something>` has the same functions as `Album`, but they don't take a conn?

**Comment by adamzaninovich** [comment]
Actually, nevermind all that. I think the problem is that this is a Spotify library that is tightly coupled to Plug.Conn, maybe the library shouldn't ever touch Conn or whatever other auth storage solution the user wants to use.

What if, instead of passing in a conn, you pass in a `%Spotify.Auth{}` struct. Then we would have `Spotify.Auth.from_session(conn)` and maybe something like `Spotify.Auth.from_agent(pid)`.

`Spotify.Album.get_album(conn, "4")` would become

```
conn
|> Spotify.Auth.from_session
|> Spotify.Album.get_album("4")
```

Of course in Phoenix, you could have a controller plug that creates this auth struct for you automatically.

**Comment by jsncmgs1** [comment]
I believe the vast majority of use cases will be web related, at least that was my intention with the library.  For that reason I'd like to keep the signatures for the existing public API the same, like what you brought up with the auth struct. Maybe we could just let the client be a little smarter and handle pids if we set the auth in an agent after we get the tokens?

``` elixir
Spotify.Album.get_album(conn_or_pid, "4")

defmodule Spotify.Client do
  @moduledoc false

  def get(pid, url) when is_pid(pid) do
    # get token from agent stuff and make request
  end

  def get(%Plug.Conn{} = conn, url) do
    HTTPoison.get(url, get_headers(conn))
  end
```

Thoughts?

**Comment by jsncmgs1** [comment]
Forgot to mention change the auth to handle a pid as well

**Comment by adamzaninovich** [comment]
Yeah, I like that direction, but I don't want to couple this to something else like Agent, or even a pid.

What if those functions accept either a `Plug.Conn` or a `Spotify.Auth` struct? That way if one didn't want to use conn, they would have complete control over how they store the auth. Then in `Client`:

``` elixir
defmodule Spotify.Client do
  @moduledoc false

  def get(conn_or_auth, url) do
    HTTPoison.get(url, get_headers(conn_or_auth))
  end

  # ----8<----

  def get_headers(conn = %Plug.Conn{}) do
    [{"Authorization", "Bearer #{conn.cookies["spotify_access_token"]}" }]
  end
  def get_headers(%Spotify.Auth{access_token: token}) do
    [{"Authorization", "Bearer #{token}" }]
  end
end
```

That way, it's up to the user how they want to store the token.

**Comment by adamzaninovich** [comment]
Cool, I'll see what I can do about an implementation. Thanks for discussing!

**Comment by jsncmgs1** [comment]
No prob. Thanks for the help!

**Comment by jsncmgs1** [comment]
FYI I have changes on the development branch.  Master is the latest hex version.

**Comment by adamzaninovich** [comment]
I branched off of master, is that ok? I'm almost ready to submit a PR.

**Comment by jsncmgs1** [comment]
That's ok, just submit PR to development and I'll handle the merge.

**Comment by adamzaninovich** [comment]
Sounds good.
