### ISSUE TITLE
handle expired access tokens

### ISSUE THREAD

**Issue by snjnlsn** [jsncmgs1/spotify_ex#41]
Hi Jason! I'm using this wrapper for a personal project, and I'm doing some work to add expiration date handling into this wrapper. Just started looking into it, but my current approach is to add spotify's 'expires_in' field to the Credentials struct and authentication flow. I'd be happy to make a PR if you're interested!

**Comment by johnurbanik** [comment]
@sanjaynelson definitely interested. Looks like @jsncmgs1 isn't super actively developing, so I'd also be open to a fork if you're willing.

**Comment by jsncmgs1** [comment]
Heya, my dev work is done in private repos these days but I’m still around :). I’m happy to merge a solid solution.
